import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'midnight-cacao-cake',
    name: 'Midnight Cacao Cake',
    price: 48.00,
    description: 'An immersive dark chocolate experience. Layered with 85% single-origin Tanzanian cacao mousse.',
    longDescription: 'An immersive dark chocolate experience. Layered with 85% single-origin Tanzanian cacao mousse, smoked sea salt caramel, and a flourless obsidian sponge. Finished with a mirror-glass glaze and hand-applied gold leaf.',
    ingredients: 'Single-origin cacao, organic heavy cream, Madagascar vanilla bean, smoked sea salt, artisanal butter, gold leaf.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPA0SWtwD_KYyYWN_QU2SQ-jwjnJ1EpEpxCf4yV1iVbgI2zfLVn_OlMnOs7mORBjTdlGcQh9R1oKLwE1smcnbKkgZI2ui0X_5bAmFZKDrbnir64TuGprFyzJ9za3Rp1Nbh0NYAwgKK-UgabnegU7ZFbMy__2Nklik6WwFMcVXRVdDjF5ZQugSPdZdqH7l2hLbx26G8fJo9tpXpEks-fRGwXE-VQOUA4v1LB8txOU3xJLVMY7uuBh-KN0Qhi2BkocH4UdbjQtPEJGoc',
    category: 'Cakes',
    collection: 'Signature Collection',
    isLimitedEdition: true,
  },
  {
    id: 'pistachio-rose-ganache',
    name: 'Pistachio Rose Ganache',
    price: 14.00,
    description: 'A delicate artisan pastry featuring a pale green pistachio ganache and a crystalline rose-water glaze.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxzMBSFSsmpg4D_gN-rT_ylNG1ThXPaEim-9jPQnteM-eia3k7jeQh3LvXKmu9IENaulCsJhQG5MJzHWPG-p2fshSCdMXAtLvEeBgMjmkYJn4t3vcBlec6vs7RIC7CWBC_MMoU3_LD3poIZI0ccPmZAmTsXd8yUrr8KKm0-_BY-HWK3XpGXIJu5eSPYtorRI93leeBmybmg2VzDikbQ6w2YHHrRKcI2EdIKDIs9UcDhY2mun4nU-9Vrr8cBjqLsaxDlzrw-GUNghlu',
    category: 'All',
    collection: 'Nut Collection',
  },
  {
    id: 'salted-honey-tart',
    name: 'Salted Honey Tart',
    price: 12.00,
    description: 'A sophisticated honey tart with a golden, crumbly pastry shell and a translucent amber honey filling.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLWuzTBMITePyehc9ggLBn6oS6UpqT5VZ2n7klX6pTt5JG6EmESKRBQR5VHl9SoxLFsA2da5iTObRiQAoMeR8LcX1Bogx8f3pU4xkKfT09nvuxM8MerGQuEi1mNRsI74cw-i7VqC4ix9_qsgeNVM6MA4nU3bGeWTozxlIYUYzbcaDa1LcQLb2uKQyS2S3iJNgB5NJjsvlKToklDEtnXJcIGWvjhH3Nio7ybB-4bCQcQZFDo6JRKIsMWT8sjqie2Eo2nlDxZWqo0Fba',
    category: 'Seasonal',
    collection: 'Seasonal Special',
  },
  {
    id: 'cacao-nib-macarons',
    name: 'Cacao Nib Macarons',
    price: 18.00,
    description: 'A stack of three perfectly smooth, charcoal-colored macarons with a creamy white chocolate filling.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArhJyzj2tdxY0Y774EevMZ-Yf0Q6kjr_KIkYZVrMOvoarE4Ptaftx4kpjC8EVuFKZOzMHHbOa_HaDqjztjiJAHjWNWNf4dlpaiPxEFOoSl05_UMamgG0lHVI04Z_KFTcB5gk0HfaD-9V4gsvjKnot2D22dJ82-IfVggQ_oi1SRqTjYxnLTKBAdlOBIGOY1mXorTWqL2dPnTCTOEoH14HzsAm79eTUHNyvPlxWxywR99tF92tIqBio6fQDRV0wdjHctgLISYO-IcmAT',
    category: 'Cookies',
    collection: 'Petite Bites',
  },
  {
    id: 'noire-velvet',
    name: 'Noire Velvet',
    price: 65.00,
    description: '70% dark Cacao sponge with infused roseberry ganache and a silk matte finish.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAOAgLkZKnm3UZfYrxdC50J_qL-stiDdhQRFYecv8RK7Ojum4It7-ORo1hlSe_Yk_Gd-9L9VwYVDbMJPGyXUFjxXfNvkLMZG--M0Lg2nMiWZlWlxk0yY7sWujrLZT7cp4W7dFCzLZCFl_pWNAiL-Ogv5WmPiC7wOVWAF1dP4snFwxkOzy0779v7rUsgQP4y27mFZXBb9rJCX-_j1RGU5iSF-Lp0ypddjwLUFHCWO9CIMBAKY6RjHh6AXCKGhlpLnQjD9PRhUYfmYb6l',
    category: 'Cakes',
  },
  {
    id: 'pastel-anthology',
    name: 'Pastel Anthology',
    price: 42.00,
    description: 'A curated selection of twelve macarons featuring seasonal floral and nut infusions.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuADz2NeuK0Q1Wpz3K8ERKEc9TxwARpC4sjiDEAGDsAFB1s7pPhYgsNYLy_PjIu-NNXn3YR-RXyT332C1oJYw728WVZPGPwAT_HHTBsV5vCNn34xs0r3EXAmredlT26OgejrY7PEADzzoRUOey-1Hc1PvB4NcBhtf0KQTiiXaTIGFRmzhVa78QQIjy3u_u8o2S8M-kccEZdKIjNIO2dWnanEInd_rIuPlyZxEdO6oo1BJKalNE_YwqVlG2KL2iy28J5IBl7LERDgsw1w',
    category: 'Gift Boxes',
  },
  {
    id: 'citron-lumine',
    name: 'Citron Lumine',
    price: 18.00,
    description: 'Sicilian lemon curd on a shortcrust base with torched Italian meringue and gold leaf.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdcrButCqTYwLlAHp2o279vedrAxyrt9Lssv6YFlxYeUvzGG0ih5riwydWErDSjspOjtp1F_4cN7_K3_b47VLWDaL7JH6mFuZupyVaafRYaCIeJmMlNr-1tAahD8e_SRCeuq8XU437nijm5VZFfwUoyZGXMv_VOBonFko3RMzByAJOB7FWw8wnkpMqru6fprbuDNQWfu86NNXSZqJE80VvQk3X989TYWC41OOeBKMCvl_9EzHQIx8nUmJftx9eG4QDT3dEI15JRqer',
    category: 'Cakes',
  },
  {
    id: 'berry-geometric',
    name: 'Berry Geometric',
    price: 22.00,
    description: 'Architectural mousse cake with wild berry center and toasted pistachio brittle.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsVYm8Jj9sGgr0tItuNgovIAHWomMzKuORpRVau3uM6iSXWv5C42sa2ZRL8Ix0_M33MG6OgA74m1M74yg3Yib6BmU4H7ky7u4twkhIwwjnVIodKCGa35aypLTu3CrtbIv8u58yV8Lipr7wSCfXfzsQfzrSXBblqye72P-tuBBqW3nLRaeT8SeLc4sJOFy-V4gbGoir2PPxk0kKwPqP1e53nArC2MjTPksqYcF5zxQf1d-I-j-jVjotLCbyVePMmdVkklMiMIkiD-HP',
    category: 'Cakes',
  },
  {
    id: 'salted-cacao',
    name: 'Salted Cacao',
    price: 28.00,
    description: 'Soft-baked cookies with single-origin chocolate chunks and hand-harvested Fleur de Sel.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5MRJRcRHO_v3CGknE8Wk9zBeuyTlM05JsxOtZuVLxaX1jzOAKzgbI3S3xTMXv6QJtOH0mNJOh6PdfuDXr89aqf-nxsD8GRyVj6eVOCsf9p_Jis6ew3sdHQCbyVjYBZcAJScFUsYAv4eArtnklN_y4-pIZAcy1KlnQ0xFQULxmwdtjEtG6tgnE-kYbBaOmaZ7ymdiiRL5tjsebtLLpSv5USgFVGgKfi5M20XqHDZxpf3zqSo7s6ooUncbzCkY_Ol6JetuHHsMqZPIy',
    category: 'Cookies',
  },
  {
    id: 'the-winter-chest',
    name: 'The Winter Chest',
    price: 110.00,
    description: 'Our largest collection of seasonal truffles, biscuits, and limited edition cocoa blends.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4BE_ALpdKw5ean7hNmAMne3X7qqvdOxnYHvdUnCTZAScYKCqe9PcyVUCI9Yvpg-jNdzciXAsD7g3GfDaCfLJNSZJrtFOy8F4eS3veYcRZOcQSfpwRJkeM7xuEFnriSPHse8PEd8ravKFDXei0E4FD-3sbBwng6fNBHE6swmvzHpnTRVpRvEeyL7gTcRDtBwOYtaK3bP_nc20m_9ID6l-5kDlFV7NwZkMyAkDmh8yj3V8T12nYn3YDagVGK_KfH4xu3jU4uADTlbUe',
    category: 'Gift Boxes',
  },
  {
    id: 'signature-cacao-truffles',
    name: 'Signature Cacao Truffles',
    price: 42.00,
    description: '72% Single Origin Peruvian Cacao dusted with fine gold powder.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDl_ExIYawfIZ9YHVqy4t510ijoUhTYJtRID1V82TkGE-uYePOKs9cEdPgrXuUcP1zYCxtH6muWDSamLw3HpNeAHfcjnBd7s0sWRhgjziPOkqaNWVwTszXIZ99VcBCAWWTa7QgIPRb5FoWdSfaHWoVrWMDWP5r_kswslwJNtT_uY8zCsEAZgBQmI90gR6-S0TuDH88IufwVyYk2lNZeRATtl4h0TKtB8eXcokNt4V4LD8MTniv5eHqwh-MbHqjq0GH0OpLhivQNuDRa',
    category: 'All',
    collection: 'Handcrafted',
  },
  {
    id: 'berry-glaze-macarons',
    name: 'Berry Glaze Macarons',
    price: 36.00,
    description: 'Wild Raspberry & Rose Infusion with vibrant berry glaze.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA6h-ZhRcVVj3GzfQqrcsR5U1UxMErqrccOcKjrR53qb_Zaza6Y99LIh_jYzxAp5sATdjohXp1BhjPFwESklbgw3WwqMn2MVVA-b_jo_FVtx9VFCO-mMciweFuFAvyq6P708_DvA4UZXgdEDD-_MCwEPJLkbF-_OJpDHo_FKNtiFw8Xo4IXNG_6XYhVsat-nMu4X6MWcmUSeSmcBPiQpUyrjFytY8VQyk00DuO_APpWsYB2XiXVOhp1QDrzcaEu8--4lXXbxgLAuWpJ',
    category: 'Seasonal',
    collection: 'Seasonal',
  },
  {
    id: 'velvet-almond-cake',
    name: 'Velvet Almond Cake',
    price: 58.00,
    description: 'Toasted Sicilian Almonds & Vanilla with a dense, moist sponge.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBSMlXaHyjopuC-h2SCVVZAwISEVpNN3FeIArTd_Q9V8f2HxlmfoHl40Wtth7IPXRxMXfu_-pDHUW_pfOAmyFxhWVdB3QnllcqjrBSX838QMWDha-N_h9sG2vtE2Sp-6-t29RT6XpSw_5cGYh1Uqo_JZPXksBYJuogMD3n3snkIJR_2eydcUXYM2QzF7b7KmuRNRlLkEuh_fpifjgIUi_sdSgsf6VpsbcsQ74RVtLe4fBCaVFSMAd5EUy0u1hNjr7j_0Qa5o2xLqIBz',
    category: 'Cakes',
    collection: 'Signature',
  }
];
